# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Max's Mutts
email: max@maxsmutts.com
description: Dog walking services for Barangaroo, Sydney CBD and Sydney's North Shore
url: "http://maxsmutts.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
instagram_username: maxsmutts

# Address information
address_street: 3034 Melrose Place
address_city: Beverly Hills
address_state: CA
address_zip: 90201

# Build settings
markdown: kramdown
