# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JV Internet Solutions
email: contact@jvinternetsolutions.com
description: Software development with a focus on innovative, leading practice solutions to problems
url: "http://jvinternetsolutions.com" # the base hostname & protocol for your site

linkedin_username: https://au.linkedin.com/in/joshvawdrey
# Address information
address_city: Sydney
address_state: NSW 

# Build settings
markdown: kramdown
